name: Run Custom GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f1001072@ds.study.iitm.ac.in
        run: echo "Hello, GitHub Actions!"

      - name: Log system info
        run: uname -a
